import Link from "next/link";
import { AcademicCapIcon, ArrowRightIcon, BuildingOffice2Icon, ClipboardDocumentCheckIcon, DocumentTextIcon, ExclamationTriangleIcon, UserGroupIcon, UserMinusIcon } from "@heroicons/react/24/outline";
import { Tile } from "@/components/ui/tile";
import type { AdminDashboardStats } from "@/lib/types/api";

export function AdminDashboard({ stats }: { stats: AdminDashboardStats }) {
  const cards = [["Today's examinations", stats.todaysExaminations ?? 0, AcademicCapIcon, "/examinations", "ink"], ["Present", stats.present ?? 0, ClipboardDocumentCheckIcon, "/attendance", "green"], ["Absent", stats.absent ?? 0, UserMinusIcon, "/attendance", "red"], ["Attendance rate", stats.attendancePercentage == null ? "—" : `${stats.attendancePercentage}%`, ClipboardDocumentCheckIcon, undefined, "gold"], ["All incidents", stats.totalIncidents ?? 0, ExclamationTriangleIcon, "/incidents", "red"], ["Generated reports", stats.generatedReports ?? 0, DocumentTextIcon, "/reports", "default"]] as const;
  return <div className="space-y-8"><section className="flex flex-col gap-4 rounded-[10px] border-l-4 border-unza-gold bg-white p-5 shadow-[0_10px_30px_rgba(15,23,42,0.04)] md:flex-row md:items-center md:justify-between"><div><div className="flex items-center gap-2"><UserGroupIcon className="h-5 w-5 text-unza-green"/><p className="text-xs font-semibold uppercase tracking-[0.16em] text-unza-green">Next step</p></div><h2 className="mt-2 text-xl font-bold text-ink">Prepare invigilator coverage</h2><p className="mt-1 max-w-2xl text-sm text-muted">Review venue staffing, generate draft assignments, and publish them when the examination plan is ready.</p></div><Link href="/assignments" className="inline-flex h-11 shrink-0 items-center justify-center gap-2 rounded-[10px] bg-ink px-4 text-sm font-medium text-white transition hover:bg-ink/90">Open assignment control room <ArrowRightIcon className="h-4 w-4"/></Link></section><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([title,value,Icon,href,accent])=><Tile key={title} title={title} value={value} icon={<Icon className="h-6 w-6"/>} href={href} accent={accent} interactive={Boolean(href)}/>)}</div><section className="rounded-[10px] bg-white p-5 shadow-[0_10px_30px_rgba(15,23,42,0.04)]"><div className="mb-4"><h2 className="text-lg font-semibold text-ink">Venue occupancy</h2><p className="text-sm text-muted">Allocated and checked-in students across current examination venues.</p></div>{stats.venueOccupancy?.length ? <div className="grid gap-3 md:grid-cols-2">{stats.venueOccupancy.map((row,index)=><article key={`${row.examSessionId}-${row.venueId}-${index}`} className="rounded-[10px] bg-surface-muted p-4"><div className="flex justify-between"><p className="font-semibold text-ink">{row.venueName ?? "Venue"}</p><BuildingOffice2Icon className="h-5 w-5 text-muted"/></div><p className="mt-1 text-sm text-muted">{row.courseCode ?? "Examination"}</p><p className="mt-3 text-sm text-ink">{row.checkedInStudents ?? 0} checked in · {row.allocatedStudents ?? 0} allocated / {row.capacity ?? "—"} capacity</p></article>)}</div> : <p className="py-8 text-center text-sm text-muted">No venue occupancy data is available today.</p>}</section></div>;
}
