"use client";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Field, Input, Select } from "@/components/ui/field";
import { Tile } from "@/components/ui/tile";
import { formatTime } from "@/lib/utils";
import type { AttendanceRecord, AttendanceSummary, Examination } from "@/lib/types/api";
const tone=(s:string)=>s==="PRESENT"?"success" as const:s==="ABSENT"?"danger" as const:s==="WRONG_VENUE"?"warning" as const:"neutral" as const;
export function AttendanceWorkspace({ examinations, selectedId, records, summary }: { examinations: Examination[]; selectedId?: number; records: AttendanceRecord[]; summary: AttendanceSummary | null }) { const router=useRouter(),[filter,setFilter]=useState(""); const rows=useMemo(()=>{const q=filter.toLowerCase();return records.filter(r=>!q||r.studentName.toLowerCase().includes(q)||r.computerNumber.toLowerCase().includes(q)||r.attendanceStatus.toLowerCase().includes(q));},[filter,records]); return <div className="space-y-6"><div className="grid gap-4 lg:grid-cols-2"><Field label="Examination session"><Select value={String(selectedId ?? "")} onChange={e=>router.push(`/attendance?examSessionId=${e.target.value}`)}>{examinations.map(e=><option key={e.examSessionId} value={e.examSessionId}>{e.courseCode} · {e.examDate} · {e.status}</option>)}</Select></Field><Field label="Filter register"><Input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Name, computer number, status"/></Field></div><div className="grid gap-4 sm:grid-cols-4"><Tile title="Checked in" value={summary?.checkedIn ?? summary?.present ?? "—"} accent="green" interactive={false}/><Tile title="Absent" value={summary?.absent ?? "—"} accent="red" interactive={false}/><Tile title="Scripts collected" value={summary?.scriptsCollected ?? "—"} accent="gold" interactive={false}/><Tile title="Incidents" value={summary?.incidents ?? "—"} accent="default" interactive={false}/></div><section className="rounded-[10px] bg-white p-5 shadow-[0_10px_30px_rgba(15,23,42,0.04)]"><h2 className="text-lg font-semibold text-ink">Attendance register</h2><p className="mb-4 text-sm text-muted">Read-only administrator oversight · {rows.length} students shown</p><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr className="border-b border-black/5 text-muted"><th className="p-2">Student</th><th className="p-2">Computer #</th><th className="p-2">Venue</th><th className="p-2">Status</th><th className="p-2">Check-in</th><th className="p-2">Scripts</th></tr></thead><tbody>{rows.map(r=><tr key={`${r.computerNumber}-${r.checkInTime}`} className="border-b border-black/5"><td className="p-2 font-medium text-ink">{r.studentName}</td><td className="p-2 font-mono">{r.computerNumber}</td><td className="p-2 text-muted">{r.venueName ?? "—"}</td><td className="p-2"><Badge tone={tone(r.attendanceStatus)}>{r.attendanceStatus}</Badge></td><td className="p-2 text-muted">{formatTime(r.checkInTime)}</td><td className="p-2">{r.scriptsSubmitted ? "Submitted" : "—"}</td></tr>)}{!rows.length&&<tr><td colSpan={6} className="p-10 text-center text-muted">No attendance records for this examination.</td></tr>}</tbody></table></div></section></div>; }
